"""empty message

Revision ID: 5a6fdb225e05
Revises: 
Create Date: 2021-05-09 09:59:19.608569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a6fdb225e05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likememory',
    sa.Column('likeid', sa.BigInteger(), nullable=False),
    sa.Column('postid', sa.Numeric(), nullable=False),
    sa.Column('likinguser', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('likeid')
    )
    op.create_table('userinfo',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password_salt_hash', sa.String(length=500), nullable=False),
    sa.Column('salt_key', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('userposts',
    sa.Column('postid', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('posts', sa.String(length=5000), nullable=True),
    sa.Column('postdate', sa.Time(), server_default=sa.text('now()'), nullable=True),
    sa.Column('sessionid', sa.String(length=300), nullable=True),
    sa.Column('likes', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('postid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userposts')
    op.drop_table('userinfo')
    op.drop_table('likememory')
    # ### end Alembic commands ###
